### ISSUE TITLE
log in error

### ISSUE THREAD

**Issue by kendra-collinsville** [Azavar/beta-ultra#2]
I get this screen when I try to log in to ultra

![ultra issue](https://cloud.githubusercontent.com/assets/26388013/23954314/f611f768-0964-11e7-8998-98831882d863.png)

**Comment by muaz-azavar** [comment]
Hi Kendra,
We figured out the issue and it has to do with the length of the phone number, we'll fix it this afternoon and let you know.

Thanks

**Comment by muaz-azavar** [comment]
Should be fixed now and ready for re-testing.

**Comment by NickChivers** [comment]
Hi Kendra, Were you able to re-test this issue and see if it is fixed to your satisfaction?

**Comment by kendra-collinsville** [comment]
Yes--for some reason, when I went back to comment it was working, it didn't give me the comment box. Thanks!

**Comment by NickChivers** [comment]
Absolutely!  I'll close this issue now.  Thanks for catching this!
