### ISSUE TITLE
image upload issue

### ISSUE THREAD

**Issue by kendra-collinsville** [Azavar/beta-ultra#5]
When testing the program from an iPad and taking a photo of the utility bill:
I select "Take Photo" as the upload option
I take the picture
I select "Use Image"
It goes back to the page for uploading bills, but it does not upload the photo I just took
If I select "Skip this month" it tells me I need to upload an image or choose "Skip this month"

Taking the picture worked just fine for uploading my ID and low income documentation

**Comment by muaz-azavar** [comment]
We'll be looking into it and we'll let you know once we have a resolution.

**Comment by muaz-azavar** [comment]
The issue should be fixed now and ready for re-testing.

**Comment by kendra-collinsville** [comment]
It is working now, thanks!

**Comment by NickChivers** [comment]
Excellent!  Glad it's working!  We'll close this bug now.
